name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy to server
    
      run: |
        sshpass -p "518321ee239d14ee837264dea0" ssh -o StrictHostKeyChecking=no root@64.23.241.172 'bash -s' < /var/www/lavels/MVGBuilder/deploy.sh
