name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get install -y sshpass
    - name: Debug output
      run: |
          set -x

    - name: Deploy to server
    
      run: |
        sshpass -p "$Ss1234565" ssh -o StrictHostKeyChecking=no root@64.23.241.172 'bash -s' < deploy.sh
        deploy.sh
